### ISSUE TITLE
Foot Commands

### ISSUE THREAD

**Issue by JuanBarron2001** [JuanBarron2001/tester#7]
1. Jump - static number activated by a button.
2. ManualJumpCommand - used by a joystick?
3. MotionMagicClimbCommand - used by a button?

Which commands are we using and how will we use them with controls?

**Comment by chadr03** [comment]
I would say for now use the Jump - static number actuated by the button since we know that worked well.  I would also like to keep the joystick version just in case we have a low battery at the end of a match and .6 isn't enough to get us up.

I think with some testing we could get motion magic and added to a button, but it is not ready for prime time yet.

I have been playing around with some methods to increase the button count on a controller.  If you look at my latest commit on my repository.

[https://github.com/chadr03/tester/tree/crMotionMagic](url)

It uses x, a, and b for hatch stuff

then lb+x, lb+y, lb+a, lb+b for cargo stuff.

Not sure if anyone would like this, but thought it might be worth looking into.  Also the TongueMoveCommand allows the use of the right y axis to move the Tongue in our out.

your welcome to use these or not I was just seeing what could be done.  I don't have a bot with all of the subsystems, but the console print outs make it seem like it works.
